language: php
dist: trusty
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
  - 'hhvm'
matrix:
  allow_failures:
    - php: nightly
install:
  - composer install
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v
